regular_scraps = ["https://pinboard.in/popular/",
        "https://pinboard.in/popular/wikipedia/",
        "https://pinboard.in/t:psychology/"]

scraps = ["https://pudding.cool/archives/"
        ]

rss_feeds = ["https://pudding.cool/feed/index.xml",
            "http://feeds.feedburner.com/brainpickings/rss"
            ]

reddit_threads = [
        '6emsam',
        'f937om',
        '9u871x',
        'fy2j5o',
        '1lnnyn',
        '5sqzle',
        '9l13yf',
        '93c1t0'
        ]

subreddits = ['InternetIsBeautiful',
            "Articles"
            ]

sites = ["https://c.xkcd.com/random/comic/",
        "https://en.wikipedia.org/wiki/Special:Random",
        "https://www.brainpickings.org/surprise/",
        'https://theoatmeal.com/feed/random',
        "https://pudding.cool/2018/08/pockets/",
        "https://www.reddit.com/r/random",
        "https://longform.org/lists/best-of-2019/",
        "https://longreads.com/2019/12/09/longreads-best-of-2019-all-of-our-no-1-story-picks/",
        "https://www.theguardian.com/news/2019/dec/24/the-best-of-the-long-read-in-2019",
        "https://www.nytimes.com/2019/12/27/t-magazine/best-long-reads.html",
        "https://www.newyorker.com/culture/2019-in-review/the-top-twenty-five-new-yorker-stories-of-2019",
        "https://www.washingtonian.com/2019/12/23/washingtonian-best-longreads-of-2019/",
        "https://foreignpolicy.com/2019/12/27/best-deep-dives-2019-longform-long-reads/",
        "https://www.wired.co.uk/article/the-best-wired-long-reads-of-2019",
        "https://rave.dj/3Rypux2q83C7Bw",
        "https://gravity-doc.com/",
        "https://neal.fun/",
        "https://theuselessweb.com/",
        "http://heeeeeeeey.com/",
		"http://corndog.io/",
		"https://alwaysjudgeabookbyitscover.com",
		"http://thatsthefinger.com/",
		"http://cant-not-tweet-this.com/",
		"http://weirdorconfusing.com/",
		"http://eelslap.com/",
		"http://www.staggeringbeauty.com/",
		"http://burymewithmymoney.com/",
		"https://smashthewalls.com/",
		"http://endless.horse/",
		"http://www.trypap.com/",
		"http://www.republiquedesmangues.fr/",
		"http://www.movenowthinklater.com/",
		"http://www.partridgegetslucky.com/",
		"http://www.rrrgggbbb.com/",
		"http://beesbeesbees.com/",
		"http://www.koalastothemax.com/",
		"http://www.everydayim.com/",
		"http://randomcolour.com/",
		"http://cat-bounce.com/",
		"http://chrismckenzie.com/",
		"https://thezen.zone/",
		"http://hasthelargehadroncolliderdestroyedtheworldyet.com/",
		"http://ninjaflex.com/",
		"http://ihasabucket.com/",
		"http://corndogoncorndog.com/",
		"http://www.hackertyper.com/",
		"https://pointerpointer.com",
		"http://imaninja.com/",
		"http://drawing.garden/",
		"http://www.ismycomputeron.com/",
		"http://www.nullingthevoid.com/",
		"http://www.muchbetterthanthis.com/",
		"http://www.yesnoif.com/",
		"http://lacquerlacquer.com",
		"http://potatoortomato.com/",
		"http://iamawesome.com/",
		"http://www.pleaselike.com/",
		"http://crouton.net/",
		"http://corgiorgy.com/",
		"http://www.wutdafuk.com/",
		"http://unicodesnowmanforyou.com/",
		"http://www.crossdivisions.com/",
		"http://tencents.info/",
		"http://www.patience-is-a-virtue.org/",
		"http://pixelsfighting.com/",
		"http://isitwhite.com/",
		"https://existentialcrisis.com/",
		"http://onemillionlols.com/",
		"http://www.omfgdogs.com/",
		"http://oct82.com/",
		"http://chihuahuaspin.com/",
		"http://www.blankwindows.com/",
		"http://dogs.are.the.most.moe/",
		"http://tunnelsnakes.com/",
		"http://www.trashloop.com/",
		"http://www.ascii-middle-finger.com/",
		"http://spaceis.cool/",
		"http://www.donothingfor2minutes.com/",
		"http://buildshruggie.com/",
		"http://buzzybuzz.biz/",
		"http://yeahlemons.com/",
		"http://wowenwilsonquiz.com",
		"https://thepigeon.org/",
		"http://notdayoftheweek.com/",
		"http://www.amialright.com/",
		"http://nooooooooooooooo.com/",
		"https://greatbignothing.com/"]